<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.codehaus.mojo.flatten.its</groupId>
    <artifactId>parent-depMngt</artifactId>
    <version>2</version>
    <relativePath/>
  </parent>
  <groupId>org.codehaus.mojo.flatten.its</groupId>
  <artifactId>repository-common-parent</artifactId>
  <version>LOCAL</version>
  <packaging>pom</packaging>
  <modules>
    <module>module-parent</module>
    <module>child</module>
  </modules>
  <properties>
    <repository.property>repository-value</repository.property>
    <revision>1.2.3.4</revision>
  </properties>
  <profiles>
    <profile>
      <id>active-parent-profile</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <active.parent.property>profile-value</active.parent.property>
      </properties>
    </profile>
  </profiles>
  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>@project.version@</version>
        <configuration>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
          <flattenRelativePathParent>true</flattenRelativePathParent>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
