<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.codehaus.mojo.flatten.its</groupId>
    <artifactId>module-common-parent</artifactId>
    <version>LOCAL</version>
    <relativePath>../module-parent/pom.xml</relativePath>
  </parent>
  <artifactId>published-child</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>
  <profiles>
    <profile>
      <id>inactive-control-profile</id>
      <activation>
        <property>
          <name>never.activate.flatten.control.profile</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>flatten-maven-plugin</artifactId>
            <configuration>
              <flattenRelativePathParent>true</flattenRelativePathParent>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
