sudo: required

language: java

# https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/9
dist: trusty

jdk:
  - oraclejdk8

env:
  - MAVEN_VERSION=3.6.3

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION} -Dhttps.protocols=TLSv1.2"

script:
  - "./mvnw --show-version --errors --batch-mode -Prun-its clean verify -Dhttps.protocols=TLSv1.2"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - joerg.hohwiller@googlemail.com
        - mojohaus@soebes.de
