<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.codehaus.mojo.flatten.its</groupId>
	<artifactId>resolve-ci-friendlies-only-with-pom-elements</artifactId>
	<version>${revision}</version>

	<properties>
		<revision>1.2.3.4</revision>
	</properties>

	<build>
		<defaultGoal>verify</defaultGoal>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<configuration>
					<flattenMode>resolveCiFriendliesOnly</flattenMode>
					<pomElements>
						<parent>remove</parent>
					</pomElements>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
