invoker.mavenOpts = -Drevision=1.2.3.4 -Drevision1=1.2.3.5 -Dsmall=small -Dsha1=abcdefg -Dchangelist=1,2,3,4
# Maven 4 and 3.10.0 requires all properties to be resolved in dependencies
invoker.maven.version = !4.0.0+,!3.10.0
